---
title: "HVM Experiments"
output: html_notebook
---

Clearing the workspace and loading some useful packages:
```{r}
rm(list=ls()) #clear the workspace
library("ggplot2")
library("pracma")
library("deSolve")
library("RColorBrewer")
library("colorspace")
library("wesanderson") #SUPER NICE COLOUR SCHEMES!
library("ggthemes")
library("tidyverse")
setwd("C:/Users/abuga/OneDrive/Desktop/DeepSeaVents-master")
source("create_landscape_func.r")
source("quasi_eq_func_w_scipy.r")
source("CTMC_func.r")
source("SRLM_ODE_func.r")
source("at_equilibrium_rootfunc.r")
source("dispersal_kernel_func.r")
source("CTMC_and_SRLM_func.r")
source("lambda_M_func.r")
source("metapop_size_at_QED.r")
```

Let's start with creating a uniform landscape of 15 patches arranged linearly:
```{r}
source("create_landscape_func.r")
landscape<-create.landscape(n.patches=10, landscape.type="linear", landscape.limit=100, 
                 patch.distribution="uniform", areas.distribution="uniform", areas.limit=1, 
                 clustering.iters=0)
print(ggplot(landscape, aes(x.coord,y.coord)) + theme_classic() + geom_point(aes(size = areas)))
n.patches<-length(landscape$patch.ID) #for future use
```
Calculate Q.E.D. (& T.qed, T.abs, rate of convergence, etc.) for various r.on and r.off combos
```{r}
qt1<-quasi.eq(n.patches=4, r.on=100, r.off=1)
enframe(qt1)

r.offs<-c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10,100,1000,10000,100000)
m<-matrix(rep(NA,12), nrow = 1, ncol = 12)
colnames(m) <- c("0.000001", "0.00001", "0.0001", "0.001", "0.01", "0.1", "1", "10", "100", "1000","10000","100000")
qt<-as_tibble(m)
for(i in 1:length(r.offs)){
  qt[i,]<-enframe(quasi.eq(n.patches=4, r.on=1, r.off=r.offs[i]))
}


r.ons<-c(1,10,100,1000,10000,100000)
r.offs<-c(1,10,100,1000,10000,100000)
m<-matrix(rep(NA,36), nrow = 6, ncol = 6)
colnames(m) <- c("1", "10", "100", "1000", "10000", "100000")
qt<-as_tibble(m)
for(i in 1:length(r.ons)){
  for(j in 1:length(r.offs)){
    q<-quasi.eq(n.patches=10, r.on=r.ons[i], r.off=r.offs[j])
    qt[i,j]<-enframe(list(QED.dist=q[1], T.absorp=q[2], rate.comparison=q[3], ratio.of.means.dist=q[4]))
  }
}
```



