---
title: "DTMC Documentation and Testing"
author: "Emma"
date: '2022-03-15'
output: pdf_document
---

```{r}
rm(list=ls()) #clear the workspace
```


```{r}
DTMC.sim<-function(timesteps, n.patches, P.mat, initial.config) {

  n<-n.patches
  
  #1. START IN THE INITIAL CONFIGURATION
  #since we'll just keep track of the state associated with each configuration
  #rather than updating the configuration over and over again in the simulation
  #let's convert the configuration in to the row/column index that corresponds to that state
  #Because of how P.mat is ordered, with the first half of the matrix rows 
  #corresponding to the first patch in the config being off, the first half 
  #of those corresponding to the 2nd patch being off as well, and so on...
  #the following algorithm should provide us with which row corresponds to 
  #our current configuration
  config<-initial.config #setting up patches in the initial configuration
  for (i in 1:n){
    if (i==1) {
      if (config[n+1-i]==0){x<-2^0} else {x<-2^1}
    } else {
      if (i>1) {
        if (config[n+1-i]==0){x<-x+0} else {x<-x+2^(i-1)}
      }
    }
  }
  
  sim.data<-c(0,x) #record t0 and the initial state
  
  #2. END IF WE BEGAN IN THE ABSORBING STATE
  if (x==1){ #if we are already in the absorbing state
    end.t<-0 #time to absorption is 0
    
    #3. OTHERWISE, PROVIDED WE'RE STILL NOT IN THE ABSORBING STATE...  
  } else { #otherwise
    for (t in 0:timesteps) { #comment out this line and end bracket if don't want to set a time limit
      #***actually can't do that in R
      while (x>1) { #while at least one patch remains on
        
        #3.1 CHOOSE WHAT THE NEXT CONFIGURATION WILL BE
        #GIVEN BY THE PROBABILITY OF TRANSITIONING TO IT FROM THE PREVIOUS STATE 
        x<-sample((1:2^n), size=1, prob=P.mat[x,]) 
        
        #3.2 UPDATE THE TIME ELAPSED IN SIMULATION
        t<-t+1
        
        #3.3 STORE THE SIMULATION DATA
        sim.data<-rbind(sim.data, c(t,x))
        
      } #end of while loop
    } #end of for loop
  } #end of else bracket
  
  #CONVERT EACH STATE "X" TO THE CONFIGURATION IT REPRESENTS:
  #1. create a dataframe with all possible configurations
  #ordered according to the sequence they occur as rows in our transition matrix
  #NOTE: updated to store these as sparse matrices to save memory :)
  all.configs <- Matrix(0, nrow=2^n, ncol=n, sparse=TRUE) #sparse matrix version
  #all.configs<-matrix(rep(NA, (2^n)*n), nrow=2^n, ncol=n) #no sparse matrix version
  for (i in 1:n){
    #if (i==1){BB<-c(0,1) #no sparse vector version
    if (i==1){BB<-as(c(0,1), "sparseVector") #sparse vector version
    }else{BB<-c(BB[1:(2^(i-2))],BB,BB[((2^(i-2))+1):(2^(i-1))])}
    all.configs[,(n-i+1)]<-t(rep(BB,2^(n-i)))}
  
  #2. use recorded state x to record the config in the simulation data
  config.data<-matrix(rep(NA, n*length(sim.data)), ncol=n, nrow=length(sim.data))
  for (i in 1:length(sim.data[,2])){
    config.data[i,]<-all.configs[sim.data[i,2],]}
  
  sim.data<-data.frame(sim.data, config.data)
  sim.data<-sim.data[1:(length(sim.data[,1])/2),] 
  #Note: for some reason there is a duplicate of the sim.data before the 
  #configs are added added to the dataframe.... can't figure out why that's 
  #happening but easy fix is just to cut that half off
  return(sim.data)
}
```


```{r}
source("quasi_eq_sparseDTMC_func.r")
stuff<-quasi.eq(n.patches=4, r.on=0.02, r.off=0.01)
sim.data<-DTMC.sim(timesteps=1000, n.patches=4, P.mat=stuff$P.mat, initial.config=c(1,1,1,1))
sim.data
```


